services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  vote:
   image: voting-app
   ports:
     - 5000:80

  worker:
     image: worker-app

  result:
    image: result-app
    ports:
     - 5001:80    

volumes:
  db-data: